DROP TABLE IF EXISTS Client;
CREATE TABLE Client
(
    id                INT AUTO_INCREMENT PRIMARY KEY,
    user_name         varchar2(100),
    email             VARCHAR(250) DEFAULT NULL,
    first_name        VARCHAR(250),
    last_name         VARCHAR(250),
    password          VARCHAR2(300),
    LAST_APPROVE_BY   VARCHAR2(50),
    LAST_APPROVE_DATE TIMESTAMP(6),
    LAST_UPDATE_BY    VARCHAR2(50),
    LAST_UPDATE_DATE  TIMESTAMP(6),
    status            varchar2(1),
    roles             varchar2(250),
    provider          varchar2(250)
);

DROP TABLE IF EXISTS Coffee;
CREATE TABLE Coffee
(
    coffee_id       INT AUTO_INCREMENT PRIMARY KEY,
    brand           VARCHAR(20),
    origin          VARCHAR(20),
    characteristics VARCHAR(30)
);

-- ALTER TABLE BATCH_JOB_INSTANCE DROP CONSTRAINT JOB_INST_UN;
-- ALTER TABLE BATCH_JOB_EXECUTION DROP CONSTRAINT JOB_INST_EXEC_FK;
-- ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP CONSTRAINT JOB_EXEC_PARAMS_FK;
-- ALTER TABLE BATCH_STEP_EXECUTION DROP CONSTRAINT JOB_EXEC_STEP_FK;
-- ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT DROP CONSTRAINT STEP_EXEC_CTX_FK;
-- ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT DROP CONSTRAINT JOB_EXEC_CTX_FK;


DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;
CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VERSION         INT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL
--     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
);

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    VERSION          INT,
    JOB_INSTANCE_ID  INT         NOT NULL,
    CREATE_TIME      DATETIME(6) NOT NULL,
    START_TIME       DATETIME(6) DEFAULT NULL,
    END_TIME         DATETIME(6) DEFAULT NULL,
    STATUS           VARCHAR(10),
    EXIT_CODE        VARCHAR(2500),
    EXIT_MESSAGE     VARCHAR(2500),
    LAST_UPDATED     DATETIME(6)
--     constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
--         references BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID INT          NOT NULL,
    PARAMETER_NAME   VARCHAR(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500),
    IDENTIFYING      CHAR(1)      NOT NULL
--     constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
--         references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  INT          NOT NULL PRIMARY KEY,
    VERSION            INT          NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID   INT          NOT NULL,
    CREATE_TIME        DATETIME(6)  NOT NULL,
    START_TIME         DATETIME(6) DEFAULT NULL,
    END_TIME           DATETIME(6) DEFAULT NULL,
    STATUS             VARCHAR(10),
    COMMIT_COUNT       INT,
    READ_COUNT         INT,
    FILTER_COUNT       INT,
    WRITE_COUNT        INT,
    READ_SKIP_COUNT    INT,
    WRITE_SKIP_COUNT   INT,
    PROCESS_SKIP_COUNT INT,
    ROLLBACK_COUNT     INT,
    EXIT_CODE          VARCHAR(2500),
    EXIT_MESSAGE       VARCHAR(2500),
    LAST_UPDATED       DATETIME(6)
--     constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
--         references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  INT           NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT
--     constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
--         references BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   INT           NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT
--     constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
--         references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);
DROP SEQUENCE BATCH_JOB_SEQ;

CREATE SEQUENCE BATCH_JOB_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 202700
    NOCACHE
    NOCYCLE;

DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 202700
    NOCACHE
    NOCYCLE;

DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 202700
    NOCACHE
    NOCYCLE;


DROP TABLE IF EXISTS UPLOAD_FILE_ERROR;
CREATE TABLE UPLOAD_FILE_ERROR
(
    ID                   INT AUTO_INCREMENT PRIMARY KEY,
    UPLOAD_FILE_ERROR    VARCHAR2(50),
    UPLOAD_FILE_ERROR_ID VARCHAR2(50),
    LINE_NUMBER          NUMBER(15),
    LINE                 VARCHAR2(4000),
    ERROR_CODE           VARCHAR2(10),
    ERROR_MESSAGE        VARCHAR2(500),
    ETL_DATE             TIMESTAMP(6),
    BATCH_NO             VARCHAR2(20)
)