package com.example.core.enums;

public enum SocketType {
    USER_CONVERSATION_UPDATED("USER_CONVERSATION_UPDATED", "CẬP NHẬT TRÒ CHUYỆN CỦA NGƯỜI DÙNG"),
    USER_CONVERSATION_ADDED("USER_CONVERSATION_ADDED", "THÊM MỚI TRÒ CHUYỆN CỦA NGƯỜI DÙNG"),

    USER_CONVERSATION_GROUP_UPDATED("USER_CONVERSATION_GROUP_UPDATED", "CẬP NHẬT TRÒ CHUYỆN NHÓM NGƯỜI DÙNG"),
    USER_CONVERSATION_GROUP_ADDED("USER_CONVERSATION_GROUP_ADDED", "THÊM MỚI TRÒ CHUYỆN NHÓM NGƯỜI DÙNG"),
    USER_CONVERSATION_GROUP_DELETE("USER_CONVERSATION_GROUP_DELETE", "XÓA TRÒ CHUYỆN NHÓM NGƯỜI DÙNG"),
    USER_MESSAGE_ADDED("USER_MESSAGE_ADDED", "THÊM MỚI TIN NHẮN CỦA NGƯỜI DÙNG"),

    USER_MESSAGE_UPDATED("USER_MESSAGE_UPDATED", "CẬP NHẬT TIN NHẮN NGƯỜI DÙNG"),
    USER_MESSAGE_DELETE("USER_MESSAGE_DELETE", "XÓA TIN NHẮN CỦA NGƯỜI DÙNG"),
    USER_MESSAGE_GROUP_ADDED("USER_MESSAGE_GROUP_ADDED", "THÊM MỚI TIN NHẮN NHÓM NGƯỜI DÙNG"),
    USER_MESSAGE_GROUP_UPDATED("USER_MESSAGE_GROUP_UPDATED", "CẬP NHẬT TIN NHẮN NHÓM NGƯỜI DÙNG"),
    USER_MESSAGE_GROUP_DELETE("USER_MESSAGE_GROUP_DELETE", "XÓA TIN NHẮN NHÓM NGƯỜI DÙNG"),
    USER_CONVERSATION_BLOCK("USER_CONVERSATION_BLOCK", "CHẶN TRÒ CHUYỆN CỦA NGƯỜI DÙNG"),
    USER_CONVERSATION_UNBLOCK("USER_CONVERSATION_BLOCK", "MỞ CHẶN TRÒ CHUYỆN CỦA NGƯỜI DÙNG"),
    USER_STATUS("USER_STATUS", "TRẠNG THÁI HOẠT ĐỘNG CỦA NGƯỜI DÙNG"),

    NOTIFICATIONS_LUCKY_WHEEL("NOTIFICATIONS_LUCKY_WHEEL","THÔNG BÁO TRÚNG THƯỞNG");

    SocketType(String id, String description) {
        this.id = id;
        this.description = description;
    }

    private String id;
    private String description;

    public String getId() {
        return id;
    }

    public String getDescription() {
        return description;
    }
}
